name: Entorno de Integracion Continua

# ¿Cuándo se va a ejecutar esto? Cuando hagamos un 'push' a la rama 'main'
on:
  push:
    branches: [ "main" ]

# ¿Qué trabajos (jobs) va a realizar el servidor?
jobs:
  build-y-test:
    # La computadora virtual que nos presta GitHub
    runs-on: ubuntu-latest

    steps:
    # 1. Copiar nuestro código del repositorio a la máquina virtual
    - name: Obtener el código
      uses: actions/checkout@v4

    # 2. Instalar Node.js en la máquina virtual
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    # 3. Instalar las dependencias (Express, Cucumber, etc.)
    - name: Instalar dependencias
      run: npm install

    # 4. Ejecutar las pruebas automáticas
    - name: Ejecutar pruebas SDD
      run: npm test

    # 5. Construir la imagen de Docker
    - name: Construir Imagen Docker (El Binario)
      run: docker build -t api-ci .

    # 6. Revisión de código con SonarCloud
    - name: Escaneo de SonarCloud
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # 7. Correo de Éxito
    - name: Enviar correo de éxito
      if: success() # Solo se ejecuta si todo lo anterior salió perfecto
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: "✅ GamerZone: Despliegue Exitoso"
        body: "¡Hola! Las pruebas automáticas del carrito y los descuentos pasaron perfectamente. La nueva versión de GamerZone se empaquetó con éxito."
        to: ignacioamartina@gmail.com 
        from: "GamerZone Bot"

    # 8. Correo de Alerta
    - name: Enviar correo de error
      if: failure() # Se ejecuta a la fuerza aunque la tubería se haya cancelado
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: "❌ GamerZone: Fallo en la tubería CI/CD"
        body: |
          ¡Alerta! El código nuevo rompió las pruebas de negocio y el despliegue fue cancelado.
          
          Para ver el motivo exacto del fallo, hacé clic en este enlace para abrir los registros del servidor:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ignacioamartina@gmail.com 
        from: "GamerZone Bot"

    # 9. Gatillo de despliegue en Render
    - name: Disparar actualización en Render
      if: success() # Solo despliega si TODO lo anterior salió perfecto
      run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"